---
name: test
on:
  push: {}
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: '${{ matrix.system.name }}'
    strategy:
      fail-fast: false
      matrix:
        system:
          - runs_on: windows-2022
            name: 'Windows x64, Go 1.23.0'
            GOARCH: 'amd64'
            GOTOOLCHAIN: 'go1.23.0'
            vs_arch: 'amd64'
            vs_path: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise'
    runs-on: '${{ matrix.system.runs_on }}'
    env:
      GOARCH: '${{ matrix.system.GOARCH }}'
      GOTOOLCHAIN: '${{ matrix.system.GOTOOLCHAIN }}'
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: test
        shell: powershell
        run: |
          # Add cl.exe to $env:PATH.
          Import-Module '${{ matrix.system.vs_path }}\Common7\Tools\Microsoft.VisualStudio.DevShell.dll'
          Enter-VsDevShell -VsInstallPath '${{ matrix.system.vs_path }}' -Arch '${{ matrix.system.vs_arch }}' -StartInPath .

          go test -v
